#:schema https://mago.carthage.software/1.40.1/schema.json
# Welcome to Mago!
# For full documentation, see https://mago.carthage.software/1.40.1/en/tools/overview/
version = "1"
php-version = "8.4.1"
editor-url = "vscode://file/%file%:%line%:%column%"

[source]
workspace = "."
paths = ["src/", "test/integration/", "test/unit/"]
includes = ["vendor"]
excludes = []

[source.glob]
literal-separator = true

[formatter]
preset = "default"
preserve-breaking-member-access-chain = true
preserve-breaking-member-access-chain-first-method-on-same-line = true
preserve-breaking-argument-list = true
preserve-breaking-array-like = true
preserve-breaking-parameter-list = true
preserve-breaking-attribute-list = true
preserve-breaking-conditional-expression = true
preserve-breaking-condition-expression = true
preserve-redundant-logical-binary-expression-parentheses = true
# custom rules
space-after-logical-not-unary-prefix-operator = true
always-break-named-arguments-list = true
align-assignment-like = true
sort-class-methods = true
preserve-breaking-binary-expression = true

[linter]
integrations = ["laminas", "phpunit"]

[linter.rules]
ambiguous-function-call = { enabled = false }
literal-named-argument = { enabled = false }
halstead = { effort-threshold = 7000 }

[analyzer]
plugins = []
find-unused-definitions = true
find-unused-expressions = true
analyze-dead-code = true
memoize-properties = true
check-throws = true
unchecked-exceptions = ["Error", "LogicException"]
unchecked-exception-classes = []
check-missing-override = true
find-unused-parameters = true
strict-list-index-checks = true
strict-array-index-existence = true
allow-array-truthy-operand = false
no-boolean-literal-comparison = false
check-missing-type-hints = true
register-super-globals = false